spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://database-1.capki1uvloci.us-east-1.rds.amazonaws.com:3306/my_db
        username: admin
        password: saikrishna

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
            javax:
                persistence:
                    validation:
                        mode: none
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    port: 8081
